---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: external-nfs-dynamic
  resources:
    requests:
      storage: 10Gi
