apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-nfs-dynamic
provisioner: nfs-storage # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
