apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          # TODO this should be dynamically established by a deployment mixin
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-storage
            - name: NFS_SERVER
              value: 192.168.100.2
            - name: NFS_PATH
              value: /volume1/temp/k8s_staging_pv
      # TODO this should be dynamically established by a deployment mixin
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.100.2
            path: /volume1/temp/k8s_staging_pv
      # Allow scheduling on gpu nodes
      tolerations:
        - key: nvidia.com/gpu
          effect: NoSchedule
          operator: Exists
