kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "external-nfs-dynamic"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
