apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: external-nfs-dynamic
  resources:
    requests:
      storage: 10Gi