apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- manifests/common/cert-manager/cert-manager/base
- manifests/common/cert-manager/kubeflow-issuer/base
# Dex
- manifests/common/dex/overlays/istio
# OIDC Authservice
- manifests/common/oidc-authservice/base
# Kubeflow namespace
- manifests/common/kubeflow-namespace/base
# Kubeflow Roles
- manifests/common/kubeflow-roles/base


# Kubeflow Pipelines
- manifests/apps/pipeline/upstream/env/platform-agnostic-multi-user
# Katib
- manifests/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- manifests/apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- manifests/apps/admission-webhook/upstream/overlays/cert-manager
# Profiles + KFAM
- manifests/apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- manifests/apps/volumes-web-app/upstream/overlays/istio
# PVCViewer Controller
- manifests/apps/pvcviewer-controller/upstream/default
# Tensorboards Controller
- manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- manifests/apps/training-operator/upstream/overlays/kubeflow
# User namespace
- manifests/common/user-namespace/base
